allowBuilds:
  esbuild: true
  sharp: true
  ttf2woff2: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/*'
  - '@expressive-code/*'
  - astro
  - astro-expressive-code
  - expressive-code
  - rehype-expressive-code
  - svelte
